# Generated by Django 3.0.6 on 2020-05-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200423_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
    ]
