# Generated by Django 3.0.6 on 2020-05-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_remove_subscribe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='longi',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
