# Generated by Django 3.0.6 on 2020-05-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200523_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longi',
        ),
    ]
