# Generated by Django 3.0.6 on 2020-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_budgetplaces_familyplaces_honeymoon_nationalparks_religious_trecking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplaces',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familyplaces',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='honeymoon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nationalparks',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='religious',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trecking',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
