# Generated by Django 3.0.6 on 2020-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20200524_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplaces',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetplaces',
            name='longi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyplaces',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyplaces',
            name='longi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honeymoon',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honeymoon',
            name='longi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nationalparks',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nationalparks',
            name='longi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='religious',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='religious',
            name='longi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trecking',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trecking',
            name='longi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
